services:
  # PostgreSQL database
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data in a named volume
    environment: # TODO: store these somewhere secure and pass in programmatically
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=pgdb
    ports:
      - "5432:5432" # Host Port:Container Port

  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - backend_data:/app/data # Named volume for backend data persistence
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://pguser:pgpassword@db/pgdb # TODO: pass these in securely
      - HOST=0.0.0.0 # Needed for FastAPI. Makes the container accessible from other containers