services:
  # PostgreSQL database
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data in a named volume
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=pgdb
    ports:
      - "5432:5432" # Host Port:Container Port